### ISSUE TITLE
Check for empty Channel Room

### ISSUE THREAD

**Issue by lamnguyencse17** [lamnguyencse17/holovn#1]
When a user leave a Channel Room, It must be checked whether there is any empty room and remove it

Task:
Write a function with MUTEX in liveRoom/data.go to:
- Loop through the whole store.
- Look for empty Room.
- Add the liveId to a separate string slice.
- Remove from store.

Hint:
- room is stored at Room.store
- Empty room <=> store[key].sockets length = 0

**Comment by TranHungKT** [comment]
This issue was fixed in liveRoom/data.go with function removeEmptyRoom().

**Comment by lamnguyencse17** [comment]
Initial Work at: https://github.com/lamnguyencse17/holovn/commit/c1fad3681963c1cc7f61b96d500b2d9dd5683813
Experienced Deadlock and Fixed at: https://github.com/lamnguyencse17/holovn/commit/d0cb3c2bf3039e918a12bafde229ae3ea5d35cc6

The issue is now closed.
